name: Deploy FAIR-CLI Binary
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  windows-py39:
    name: Deploy Latest Windows Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
          architecture: "x64"

      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Install Module
        run: python -m poetry install

      - name: Install PyInstaller
        run: poetry run pip install pyinstaller

      - name: Build Windows Binary
        run: |
          poetry run pyinstaller -c -F fair/cli.py --collect-all fair
          mv dist/cli.exe dist/fair-cli-${{ steps.previoustag.outputs.tag }}-x64-windows-latest.exe

      - uses: actions/upload-artifact@v1
        with:
            name: windows_faircli
            path: dist/fair-cli-${{ steps.previoustag.outputs.tag }}-x64-windows-latest.exe

  macos-py39:
    name: Deploy Latest macOS Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
          architecture: "x64"

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Install Module
        run: python -m poetry install

      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Install PyInstaller
        run: poetry run pip install pyinstaller

      - name: Build macOS Binary
        run: |
          poetry run pyinstaller -c -F fair/cli.py --collect-all fair
          mv dist/cli dist/fair-cli-${{ steps.previoustag.outputs.tag }}-x64-macos-latest

      - uses: actions/upload-artifact@v1
        with:
            name: macos_faircli
            path: dist/fair-cli-${{ steps.previoustag.outputs.tag }}-x64-macos-latest


  ubuntu-py39:
    name: Deploy Latest Linux Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
          architecture: "x64"

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Install Module
        run: python -m poetry install

      - name: Install PyInstaller
        run: poetry run pip install pyinstaller

      - name: Build Ubuntu Binary
        run: |
          poetry run pyinstaller -F fair/cli.py --collect-all fair
          mv dist/cli dist/fair-cli-${{ steps.previoustag.outputs.tag }}-x64-ubuntu-latest

      - uses: actions/upload-artifact@v1
        with:
            name: ubuntu_faircli
            path: dist/fair-cli-${{ steps.previoustag.outputs.tag }}-x64-ubuntu-latest


  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - ubuntu-py39
      - macos-py39
      - windows-py39
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
          architecture: "x64"

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Install Module
        run: python -m poetry install

      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Verify version alignment
        run: |
          CITATION_VERSION=$(poetry run python -c "import yaml; print(yaml.safe_load(open('CITATION.cff'))['version'])")
          MODULE_VERSION=$(poetry run python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
          GIT_TAG=${{ steps.previoustag.outputs.tag }}
          if [ "${GIT_TAG//v/}" != "${CITATION_VERSION}" ]; then
            echo "Citation version does not match latest tag"
            exit 1
          fi
          if [ "${GIT_TAG//v/}" != "${MODULE_VERSION}" ]; then
            echo "Module version does not match latest tag"
            exit 1
          fi

      - name: Build Module
        run: |
          poetry build

      - name: Retrieve Ubuntu Executable
        uses: actions/download-artifact@v1
        with:
          name: ubuntu_faircli

      - name: Retrieve Windows Executable
        uses: actions/download-artifact@v1
        with:
          name: windows_faircli

      - name: Retrieve macOS Executable
        uses: actions/download-artifact@v1
        with:
          name: macos_faircli

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          name: FAIR-CLI Release ${{ steps.previoustag.outputs.tag }}
          tag_name: ${{ steps.previoustag.outputs.tag }}
          files: |
            dist/*.whl
            dist/*.gz
            macos_faircli/fair-cli-${{ steps.previoustag.outputs.tag }}-x64-*
            windows_faircli/fair-cli-${{ steps.previoustag.outputs.tag }}-x64-*
            ubuntu_faircli/fair-cli-${{ steps.previoustag.outputs.tag }}-x64-*
