name: Deploy FAIR-CLI Binary
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  ubuntu-py39:
    name: Deploy Latest Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
          architecture: "x64"

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Install Module
        run: python -m poetry install

      - name: Install PyInstaller
        run: poetry run pip install pyinstaller

      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Verify version alignment
        run: |
          CITATION_VERSION=$(poetry run python -c "import yaml; print(yaml.safe_load(open('CITATION.cff'))['version'])")
          MODULE_VERSION=$(poetry run python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
          GIT_TAG=${{ steps.previoustag.outputs.tag }}
          if [ "${GIT_TAG//v/}" != "${CITATION_VERSION}" ]; then
            echo "Citation version does not match latest tag"
            exit 1
          fi
          if [ "${GIT_TAG//v/}" != "${MODULE_VERSION}" ]; then
            echo "Module version does not match latest tag"
            exit 1
          fi

      - name: Build Module
        run: |
          poetry build

      - name: Build Ubuntu Binary
        run: |
          poetry run pyinstaller -F fair/cli.py --collect-all fair
          mv dist/cli dist/fair-cli-${{ steps.previoustag.outputs.tag }}-x64-ubuntu-latest

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          name: FAIR-CLI Release ${{ steps.previoustag.outputs.tag }}
          tag_name: ${{ steps.previoustag.outputs.tag }}
          files: |
            dist/*.whl
            dist/*.gz
            dist/fair-cli-${{ steps.previoustag.outputs.tag }}-x64-*

    
