name: FAIR Data Pipeline CLI
on: [push]
jobs:
  test:
    name: Test ${{ matrix.os }} (Python ${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    env: HOME ./temp_registry
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest]
        python: ["3.7", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: "x64"
      - name: Install the Local Registry
        run: |
          /bin/bash -c "$(curl -fsSL https://data.scrc.uk/static/localregistry.sh)"
          $HOME/.fair/registry/scripts/start_fair_registry
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Install Module
        run: python -m poetry install
      - name: Run Tests
        run: python -m poetry run pytest --cov=fair --cov-report=xml --cov-report=term -s tests/
      - name: Stop Registry
        run: $HOME/.fair/registry/scripts/stop_fair_registry
        
