name: FAIR Data Pipeline CLI
on: [push]
jobs:
  test:
    name: Test ${{ matrix.os }} (Python ${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest]
        python: ["3.7", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: "x64"
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Install Module
        run: python -m poetry install
      - name: Run Tests
        run: python -m poetry run pytest -m "not server and not cli" --cov=fair --cov-report=xml --cov-report=term -s tests/
