name: FAIR Data Pipeline CLI
on: [push, workflow_dispatch]
jobs:
  test:
    name: Test ${{ matrix.os }} (Python ${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.8", "3.9", "3.10", "3.x"]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Create Temp Folder
        run: mkdir ../temp
        shell: bash
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: "x64"
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Install Module
        run: python -m poetry install
      - name: Install Python API for API Tests
        run: python -m poetry run pip install git+https://github.com/FAIRDataPipeline/pyDataPipeline.git@dev
      - name: Run Tests for Each Marker
        run: |
            export TMPDIR=${GITHUB_WORKSPACE}/../temp
            export TEMP=${GITHUB_WORKSPACE}/../temp
            export TMP=${GITHUB_WORKSPACE}/../temp
            for marker in $(poetry run pytest --markers | grep -oE "faircli_[a-zA-Z|_|0-9]+")
            do
              echo "Running tests for marker '$marker'"
              python -m poetry run pytest -m $marker --basetemp=${GITHUB_WORKSPACE}/../temp --cov=fair --cov-report=xml --cov-report=term --cov-append -s tests/
              exit_code=$?
              if [ "$exit_code" != "0" ]; then
                echo "ERROR: Tests for marker '$marker' failed"
              fi
            done
        shell: bash
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false
          verbose: true
