# Check latest release of all implementations still function with new changes
name: FAIR CLI Implementation Testing
on: [push]
jobs:
  Python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone Python Implementation
        uses: actions/checkout@v2
        with:
          repository: FAIRDataPipeline/pyDataPipeline
          path: python_example
          ref: 'dev'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Install local registry
        run: |
          /bin/bash -c "$(curl -fsSL https://data.scrc.uk/static/localregistry.sh)"
      - name: Install and initialise FAIR CLI
        run: |
          pip install poetry
          poetry install

      - name: run Python Model with fair cli
        run: |
          poetry run fair init --ci
          poetry run pip install .
          poetry run fair pull src/org/fairdatapipeline/simpleModel/ext/SEIRSconfig.yaml --debug
          poetry run fair run src/org/fairdatapipeline/simpleModel/ext/SEIRSconfig.yaml --debug
        working-directory: python_example

  Java:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone Java Implementation
      uses: actions/checkout@v2
      with:
        repository: FAIRDataPipeline/javaSimpleModel
        path: java_example
        ref: 'v1.0.0-alpha'
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Gradle
      run: gradle build
      working-directory: java_example
    
    - name: Install local registry
      run: |
        /bin/bash -c "$(curl -fsSL https://data.scrc.uk/static/localregistry.sh)"
    
    - name: install fair-cli
      run: |
        pip install poetry
        poetry install
    
    - name: run javaSimpleModel with fair cli
      run: |
        poetry run fair init --ci
        poetry run fair pull src/main/resources/seirs-config.yaml --debug
        poetry run fair run  src/main/resources/seirs-config.yaml --debug
      working-directory: java_example 
