# Publishes any tag which does not have a suffix
# i.e. v0.1.0 would be published but not v0.1.0-rc1, v0.1.0-beta etc.
# in addition, if the version number in the pyproject.toml has not been
# updated as it should have been then this will terminate the CI

name: Publish Release
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish_to_pypi:
    runs-on: ubuntu-latest
    name: Publish to PyPi
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve Tag
        uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "v(.*)"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Check PyProject Module Version
        run: |
          python -m pip install toml PyYAML
          MODULE_TAG=$(python -c "import toml; meta=toml.load('pyproject.toml');print(meta['tool']['poetry']['version'])" | xargs)
          CITATION_TAG=$(python -c "import yaml; meta=yaml.safe_load(open('CITATION.cff'));print(meta['version'])" | xargs)
          if [ "$MODULE_TAG" != "${{ steps.tagName.outputs.tag }}" ]
          then 
            echo "Tag mismatch between git and Python module, aborting: $MODULE_TAG != ${{ steps.tagName.outputs.tag }}";
            echo "Update the module version either using 'poetry version' command or edit the 'pyproject.toml' file."
            exit 1;
          fi
          if [ "$CITATION_TAG" != "${{ steps.tagName.outputs.tag }}" ]
          then 
            echo "Tag mismatch between git and CITATION file, aborting: $CITATION_TAG != ${{ steps.tagName.outputs.tag }}";
            echo "Update the 'version' tag in the CITATION file."
            exit 1;
          fi
      - name: Build Module
        run: |
          poetry install
          poetry build
          ls dist/
      - name: Publish Module to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}


